#! /usr/bin/perl

use Getopt::Std;
use vars qw( %opt %ConfigList);

@cmakeFiles = ('CMakeFiles', 'Makefile', 'progress.make', 'cmake_install.cmake',
               'config-bsg.h', 'CMakeCache.txt', 'DartTestfile.txt', 'Testing',
               'DartTestfile.txt', 'DartConfiguration.tcl');

# -------------------------
# Main
# -------------------------
MAIN: {

    my $opt_string = 'vh';
    getopts( "$opt_string", \%opt ) or &usage();
    if($opt{h}){ &usage(); }

    open(INPUT, "find . |") or die("Couldn't run find, Do you have find installed? Win32 maybe?");

    $count=0;

    # for each file find gives us
    # -----------------------
    while($line = <INPUT>){
        $count++;
        chomp($line);
        $line =~ s/^\? *//g;

        # clean only cmake files?
        # -----------------------
        if( &isCmake($line) ){
            if($opt{v}){ print "Removing: $line\n"; }
            system("rm -rf $line");
        }
    }

    if($count > 0){ print "Build system cleaned...\n"; }
    else{ print "No files found to clean...\n"; }
}

# -------------------------
# Subroutines
# -------------------------
sub isCmake(){
    my $file = shift; 
    foreach $item (@cmakeFiles){
        if( $file =~ /$item/ ){
            return 1;
        }
    }
    return 0;
}

#-------------------------------------------------------
# Inform the un-informed
#-------------------------------------------------------
sub usage() {
    print STDERR << "EOF";

    Usage: $0 -a -v

        Cleans the build tree of all CMake generated files

    Optional
      -v     Verbose ( Show all files removed )

     Written by: Derrick J. Wippler (Thrawn01\@gmail.com)

EOF
    exit;
}

